groups:
  - name: error
    rules:
      - alert: LogAlert
        expr: |
          sum by (level, msg, caller, info)
          (count_over_time({job="bingo", level="ERROR"} [1m]))
          > 0
        for: 0s
        labels:
        #   severity: error
        # annotations:
        #   description:
        #   summary:
