server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # - job_name: system
  #   static_configs:
  #     - targets:
  #         - localhost
  #       labels:
  #         job: varlogs
  #         __path__: /var/log/*log
  - job_name: your-service
    static_configs:
      - targets:
          - localhost
        labels:
          job: your-service
          __path__: /log-your-service/*log
    pipeline_stages:
      - json:
          expressions:
            level: level
            ts: ts
            caller: caller
            msg: msg
            trace: trace
            subject: subject
            object: object
            instance: instance
            task: task
            cost: cost
            result: result
            status: status
            ip: ip
            info: info
      - labels:
          level:
          ts:
          caller:
          msg:
          trace:
          subject:
          object:
          instance:
          task:
          cost:
          result:
          status:
          ip:
          info:
